FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache  make  g++  python3

RUN apk update && apk add ffmpeg

RUN npm install

COPY . .

RUN npm rebuild bcrypt --build-from-source

RUN apk del make g++ python3

RUN npm run build

EXPOSE 5000

CMD [ "npm","run", "start" ]